name: Release

env:
    GPR_TOKEN: ${{ secrets.GPR_TOKEN }}
    HUSKY_SKIP_INSTALL: true

on:
    push:
        branches:
            - test-master
jobs:
    release:
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14
            - name: Restore node_modules cache
              uses: actions/cache@v2
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
            - name: Install packages
              run: yarn --frozen-lockfile
            - name: Semantic Release
              uses: cycjimmy/semantic-release-action@v2
              with:
                  semantic_version: 17
                  branches: 'test-master'
                  dry_run: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.GPR_PUBLISH_TOKEN }}
        outputs:
            new_release_published: ${{ steps.semantic_dry.outputs.new_release_published }}
            new_release_version: ${{ steps.semantic_dry.outputs.new_release_version }}
